export const billingFormData = [
  {
    label: "First Name",
    name: "firstName",
    place_holder: "Enter First Name",
    error_message: "First Name is Required",
    type: "text",
    required: true,
  },
  {
    label: "Last Name",
    name: "lastName",
    place_holder: "Enter Last Name",
    error_message: "Last Name is required",
    type: "text",
    required: true,
  },
  {
    label: "Email Address",
    name: "email",
    place_holder: "Enter Email Address",
    error_message: "Email Address is required",
    type: "text",
    required: true,
  },
  {
    label: "Country",
    name: "country",
    place_holder: "Enter Country",
    error_message: "Country is required",
    type: "text",
    required: true,
  },
  {
    label: "City/Town",
    name: "city",
    place_holder: "Enter city/town",
    error_message: "Country is required",
    type: "text",
    required: false,
  },
  {
    label: "Street Address",
    name: "address",
    place_holder: "Enter your street address",
    error_message: "Street address is required",
    type: "richtext",
    required: true,
  },
  {
    label: "Phone Number",
    name: "phoneNumber",
    place_holder: "Enter Phone Number",
    error_message: "Phone Number is required",
    type: "text",
    required: true,
  },
];

export const newCategory = [
  {
    label: "Category Name",
    name: "categoryName",
    place_holder: "Enter category name",
    error_message: "Category name is required",
    type: "text",
    required: true,
  },
  {
    label: "Category Slug",
    name: "categorySlug",
    place_holder: "Enter category slug",
    error_message: "Category slug is required",
    type: "text",
    required: true,
  },
  {
    label: "Description",
    name: "description",
    place_holder: "Enter description",
    error_message: "Description is required",
    type: "richtext",
    required: true,
  },
  {
    label: "Status",
    name: "status",
    place_holder: "Enter status",
    error_message: "Status is required",
    type: "text",
    required: true,
  },
];

export const newSubcategory = [
  // {
  //   label: "Parent Category",
  //   name: "parentCategory",
  //   place_holder: "Enter parent category",
  //   error_message: "Parent category is required",
  //   type: "text",
  //   required: true,
  // },
  {
    label: "Subategory Name",
    name: "subCategoryName",
    place_holder: "Enter subcategory name",
    error_message: "Subategory name is required",
    type: "text",
    required: true,
  },
  {
    label: "Description",
    name: "description",
    place_holder: "Enter description",
    error_message: "Description is required",
    type: "richtext",
    required: true,
  },
  {
    label: "Status",
    name: "status",
    place_holder: "Enter status",
    error_message: "Status is required",
    type: "text",
    required: true,
  },
];
