export const billingFormData = [
  {
    label: "First Name",
    name: "firstName",
    place_holder: "Enter First Name",
    error_message: "First Name is Required",
    type: "text",
    required: true,
  },
  {
    label: "Last Name",
    name: "lastName",
    place_holder: "Enter Last Name",
    error_message: "Last Name is required",
    type: "text",
    required: true,
  },
  {
    label: "Email Address",
    name: "email",
    place_holder: "Enter Email Address",
    error_message: "Email Address is required",
    type: "text",
    required: true,
  },
  {
    label: "Country",
    name: "country",
    place_holder: "Enter Country",
    error_message: "Country is required",
    type: "text",
    required: true,
  },
  {
    label: "City/Town",
    name: "city",
    place_holder: "Enter city/town",
    error_message: "Country is required",
    type: "text",
    required: false,
  },
  {
    label: "Street Address",
    name: "address",
    place_holder: "Enter your street address",
    error_message: "Street address is required",
    type: "richtext",
    required: true,
  },
  {
    label: "Phone Number",
    name: "phoneNumber",
    place_holder: "Enter Phone Number",
    error_message: "Phone Number is required",
    type: "text",
    required: true,
  },
];
